void vitoria() {
printf("                                        |                                       \n");
printf("                                                                                \n");
printf("                                        |                                       \n");
printf("                                                                                \n");
printf("                                        |                                       \n");
printf("                                                                                \n");
printf("                                        |                                       \n");
printf("                                                                                \n");
printf("                                        |                                       \n");
printf("                                                                                \n");
printf("                                                                                \n");
printf("                                                                                \n");
printf("                                       /\\                                      \n");
printf("                                      /  \\                                     \n");
printf("           \\_                        /    \\                       _/          \n");
printf("             \\_                     /      \\                    _/            \n"); 
printf("               \\_                  /        \\                 _/              \n"); 
printf("                 \\_               /          \\              _/                \n");
printf("                   \\_            /            \\           _/                  \n"); 
printf("                     \\          /              \\         /                    \n");
printf("                               /                \\                              \n");
printf("                              /       _____      \\                             \n");
printf("                             /     _-       -_    \\                            \n");
printf("  _ _ _ _ _ _ _ _ _ _ _     /     <     0     >    \\     _ _ _ _ _ _ _ _ _ _ _ \n");
printf("                           /        *=_____=*       \\                          \n");
printf("                          /                          \\                         \n");
printf("                         /                            \\                        \n");
printf("                        /                              \\                       \n"); 
printf("                   _/  /                                \\  \\_                 \n"); 
printf("                 _/   /                                  \\   \\_               \n"); 
printf("               _/    /____________________________________\\    \\_             \n");
printf("             _/                                                  \\_            \n");
printf("           _/                                                      \\_          \n");
printf("                                                                                \n");
printf("                                        |                                       \n");
printf("                                                                                \n");
printf("                                        |                                       \n");
printf("                                                                                \n");
printf("                                        |                                       \n");
printf("                                                                                \n");
printf("                                        |                                       \n");
printf("                                                                                \n");
printf("                                        |                                       \n");
  
  printf("\n\n");
}